# Generated by Django 3.2.16 on 2023-02-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('district', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=70)),
                ('district', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('aplcn', models.CharField(default='Not Applied', max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('0', 'Female')], default=1, max_length=2)),
                ('address', models.CharField(max_length=200)),
                ('marital_status', models.CharField(choices=[('1', 'Single'), ('0', 'Married')], default=1, max_length=2)),
                ('photo', models.ImageField(upload_to='images')),
                ('identification_mark', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=200)),
                ('uid_aadhar_driv', models.CharField(max_length=200)),
                ('mwuid', models.CharField(max_length=200)),
            ],
        ),
    ]
